### ISSUE TITLE
unable to use Check Topological Mat. for vasp-spinor example

### ISSUE THREAD

**Issue by aali28** [stepan-tsirkin/irrep#52]
Dear Stepan

I performed DFT calculation in irrep-master/examples/C2B2Gd-vasp-spinor/dft_inputs with VASP6.3 and PAW PPs.

The command " irrep' -spinor  -code=vasp > out " gives a trace.txt file. When I upload thin on Check Topological Mat. I get " The traces for some symmetry operations at some maximal k-vector do not correspond to any direct sum of irreps in the space group given. Sometimes the problem can be solved increasing the resolution in the calculations."

I have tried other examples of Bi2Se3 and I get the same thing. 
Kindly help me with the problem and am I doing something wrong in the calculation steps?

Regards  

[trace.txt](https://github.com/stepan-tsirkin/irrep/files/9544872/trace.txt)

**Comment by MIraola** [comment]
Dear @aali28 ,

I have looked into the `trace.txt` file you attached. The reason why it does not work when you upload it to `Check Topological Mat.`  is a **typical problem of VASP** (and probably other DFT codes), **not of `IrRep`**: the convergence of the last bands is usually poor. There are 2 ways to solve this problem:

- Calculate more bands with VASP by increasing the parameter `NBANDS` in the `INCAR` file.
- Run `IrRep` by setting a value for `IBend` which leaves out of the calculation the poorly converged bands. In your case, if you use `-IBend=61`, the problem is solved (I attach the `trace.txt` you would get this way, so that you can check that it would work).

Did you 
[trace.txt](https://github.com/stepan-tsirkin/irrep/files/9554881/trace.txt)

**Comment by MIraola** [comment]
Dear @aali28 ,

the  reason why the trace.txt file might not work for some particular number of bands (`-IBend`) is that this number should always be chosen in such a way that bands are included consistently in the calculation of the traces. For example, let's imagine that my space group has at all maximal k-points only irreps of dimension 2. Then, if I choose `-IBend=21`, the last band is not properly included in the calculation of the traces. `-IBend` would have to be even.

**Comment by aali28** [comment]
Thank you
I will further look into this.

Regards
